[package]
name = "rust-idioms"
version = "0.1.0"
authors = ["Jie Yang <jie.yang@nanchao.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
